[env:ATtiny1614]
platform = atmelmegaavr
board = ATtiny1614
framework = arduino
upload_protocol = serialupdi   ; For programming via Adafruit's UPDI Friend breakout board
upload_speed = 115200 ; If UPDI initialization errors, try 57600

; To change the internal clock speeds if desired. Default is 16000000L or 20000000L
; board_build.f_cpu = 16000000L
