[platformio]
name = Wedding Keychain Keepsake
description = "An 80mm x 30mm keychain containing 32 (8 x 4 grid) interactive RGB LEDs, displaying animations and responding to sound."
default_envs = debug

[env]
upload_speed = 115200
monitor_speed = 115200

[env:virtualization]
platform = atmelmegaavr
board = ATtiny1614
framework = arduino
upload_protocol = serialupdi   ; For programming via Adafruit's UPDI Friend breakout board
build_type = debug
build_unflags = -std=gnu++11
build_flags =
	-g
	-DVIRTUALIZATION
	-std=gnu++2a
	-DUARTTX=PIN_PB2
	-DUARTRX=PIN_PB3

[env:debug]
platform = atmelmegaavr
board = ATtiny1614
framework = arduino
upload_protocol = serialupdi
build_type = debug
board_build.f_cpu = 20000000L
build_unflags = -std=gnu++11
build_flags =
	-g
	-DDEBUG
	-std=gnu++2a

[env:release]
platform = atmelmegaavr
board = ATtiny1614
framework = arduino
upload_protocol = serialupdi
build_type = release
build_unflags = -std=gnu++11
build_flags =
	-Os
	-DRELEASE
	-std=gnu++2a


; To change the internal clock speeds if desired. Default is 16000000L or 20000000L
; board_build.f_cpu = 16000000L
