[platformio]
name = Wedding Keychain Keepsake
description = "An 80mm x 30mm keychain containing 32 (8 x 4 grid) interactive RGB LEDs, displaying animations and responding to sound."
default_envs = debug

[env]
platform = atmelmegaavr
board = ATtiny1614
framework = arduino
upload_protocol = serialupdi
board_build.f_cpu = 20000000L
upload_speed = 115200
monitor_speed = 115200

[env:debug]
build_type = debug
build_unflags = -std=gnu++11
build_flags =
	-g
	-DDEBUG
	-std=gnu++17

[env:release]
build_type = release
build_unflags = -std=gnu++11
build_flags =
	-Os
	-DRELEASE
	-std=gnu++17
